/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import dao.EntregadorDAO;
import java.awt.event.KeyEvent;
import java.sql.SQLException;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.EntregadorModel;


import javax.swing.table.DefaultTableModel;
import model.Utilitarios;
/**
 *
 * @author Rosany
 */
public class TelaCadastroEntregador extends javax.swing.JFrame {
    
    public void listar(){
        EntregadorDAO dao = new EntregadorDAO();
        List<EntregadorModel> lista = dao.listarEntregadors();
        DefaultTableModel dados = (DefaultTableModel)jTablePesquisar.getModel();
        dados.setNumRows(0) ;
        
        for(EntregadorModel c : lista){
            dados.addRow(new Object[]{
            c.getCodigo(),
            c.getNome(),
            c.getCelular(),
            c.getData()
            });
        }
        
    }

    /**
     * Creates new form TelaCadastroEntregador
     */
    public TelaCadastroEntregador() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel13 = new javax.swing.JLabel();
        jTextField12 = new javax.swing.JTextField();
        jTextField1 = new javax.swing.JTextField();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanelCadastro = new javax.swing.JPanel();
        jButtonCadastrarEntregador = new javax.swing.JButton();
        jButtonAtualizarEntregador = new javax.swing.JButton();
        jButtonApagarEntregador = new javax.swing.JButton();
        jButtonExcluirEntregador = new javax.swing.JButton();
        jLabel56 = new javax.swing.JLabel();
        jTextFieldCodigo = new javax.swing.JTextField();
        jTextFieldNome = new javax.swing.JTextField();
        jLabel57 = new javax.swing.JLabel();
        jFormattedTextFieldCelular = new javax.swing.JFormattedTextField();
        jFormattedTextFieldData = new javax.swing.JFormattedTextField();
        jLabel63 = new javax.swing.JLabel();
        jLabel54 = new javax.swing.JLabel();
        jButtonPesquisarEntregador = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabelNomePesquisar = new javax.swing.JLabel();
        jTextFieldPesquisarNome = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTablePesquisar = new javax.swing.JTable();
        jButtonNovo = new javax.swing.JButton();
        jButtonPesquisarSalvar = new javax.swing.JButton();
        jButtonPesquisarEditar = new javax.swing.JButton();
        jButtonExcluirFuncionario = new javax.swing.JButton();
        jButtonPesquisar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        jLabel13.setText("UF:");

        jTextField12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField12ActionPerformed(evt);
            }
        });

        jTextField1.setText("jTextField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setAutoRequestFocus(false);
        setBackground(new java.awt.Color(255, 153, 153));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        jTabbedPane1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTabbedPane1MouseClicked(evt);
            }
        });

        jButtonCadastrarEntregador.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButtonCadastrarEntregador.setForeground(new java.awt.Color(0, 0, 153));
        jButtonCadastrarEntregador.setText("SALVAR");
        jButtonCadastrarEntregador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCadastrarEntregadorActionPerformed(evt);
            }
        });

        jButtonAtualizarEntregador.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButtonAtualizarEntregador.setForeground(new java.awt.Color(0, 0, 153));
        jButtonAtualizarEntregador.setText("ATUALIZAR");
        jButtonAtualizarEntregador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAtualizarEntregadorActionPerformed(evt);
            }
        });

        jButtonApagarEntregador.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButtonApagarEntregador.setForeground(new java.awt.Color(0, 0, 153));
        jButtonApagarEntregador.setText("APAGAR");
        jButtonApagarEntregador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonApagarEntregadorActionPerformed(evt);
            }
        });

        jButtonExcluirEntregador.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButtonExcluirEntregador.setForeground(new java.awt.Color(0, 0, 153));
        jButtonExcluirEntregador.setText("EXCLUIR");
        jButtonExcluirEntregador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonExcluirEntregadorActionPerformed(evt);
            }
        });

        jLabel56.setText("Código:");

        jTextFieldCodigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldCodigoActionPerformed(evt);
            }
        });

        jTextFieldNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldNomeActionPerformed(evt);
            }
        });

        jLabel57.setText("Nome:");

        try {
            jFormattedTextFieldCelular.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##)# ####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jFormattedTextFieldCelular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFormattedTextFieldCelularActionPerformed(evt);
            }
        });

        try {
            jFormattedTextFieldData.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        jLabel63.setText("Data:");

        jLabel54.setText("Celular:");

        jButtonPesquisarEntregador.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButtonPesquisarEntregador.setForeground(new java.awt.Color(0, 0, 153));
        jButtonPesquisarEntregador.setText("PESQUISAR");
        jButtonPesquisarEntregador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPesquisarEntregadorActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelCadastroLayout = new javax.swing.GroupLayout(jPanelCadastro);
        jPanelCadastro.setLayout(jPanelCadastroLayout);
        jPanelCadastroLayout.setHorizontalGroup(
            jPanelCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCadastroLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanelCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelCadastroLayout.createSequentialGroup()
                        .addComponent(jButtonCadastrarEntregador)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonAtualizarEntregador)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonApagarEntregador)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonExcluirEntregador))
                    .addGroup(jPanelCadastroLayout.createSequentialGroup()
                        .addComponent(jLabel56)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButtonPesquisarEntregador))
                    .addGroup(jPanelCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanelCadastroLayout.createSequentialGroup()
                            .addComponent(jLabel57)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jTextFieldNome))
                        .addGroup(jPanelCadastroLayout.createSequentialGroup()
                            .addComponent(jLabel54)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jFormattedTextFieldCelular, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(jLabel63)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jFormattedTextFieldData, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(138, Short.MAX_VALUE))
        );
        jPanelCadastroLayout.setVerticalGroup(
            jPanelCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelCadastroLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanelCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel56)
                    .addComponent(jTextFieldCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonPesquisarEntregador))
                .addGap(32, 32, 32)
                .addGroup(jPanelCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel57)
                    .addComponent(jTextFieldNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jFormattedTextFieldCelular, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel54)
                    .addComponent(jLabel63)
                    .addComponent(jFormattedTextFieldData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(148, 148, 148)
                .addGroup(jPanelCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonCadastrarEntregador)
                    .addComponent(jButtonAtualizarEntregador)
                    .addComponent(jButtonApagarEntregador)
                    .addComponent(jButtonExcluirEntregador))
                .addContainerGap(212, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Cadastro", jPanelCadastro);

        jLabelNomePesquisar.setText("Nome:");

        jTextFieldPesquisarNome.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextFieldPesquisarNomeKeyPressed(evt);
            }
        });

        jTablePesquisar.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Codigo", "Nome", "Celular", "Data"
            }
        ));
        jScrollPane1.setViewportView(jTablePesquisar);

        jButtonNovo.setText("Novo");

        jButtonPesquisarSalvar.setText("Salvar");

        jButtonPesquisarEditar.setText("Editar");
        jButtonPesquisarEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPesquisarEditarActionPerformed(evt);
            }
        });

        jButtonExcluirFuncionario.setText("Excluir");
        jButtonExcluirFuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonExcluirFuncionarioActionPerformed(evt);
            }
        });

        jButtonPesquisar.setText("Pesquisar");
        jButtonPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPesquisarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(129, 129, 129)
                                .addComponent(jButtonNovo)
                                .addGap(18, 18, 18)
                                .addComponent(jButtonPesquisarSalvar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButtonPesquisarEditar)
                                .addGap(18, 18, 18)
                                .addComponent(jButtonExcluirFuncionario))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabelNomePesquisar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldPesquisarNome, javax.swing.GroupLayout.PREFERRED_SIZE, 331, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jButtonPesquisar)))
                        .addGap(0, 94, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelNomePesquisar)
                    .addComponent(jTextFieldPesquisarNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonPesquisar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 378, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonNovo)
                    .addComponent(jButtonPesquisarSalvar)
                    .addComponent(jButtonPesquisarEditar)
                    .addComponent(jButtonExcluirFuncionario))
                .addGap(9, 9, 9))
        );

        jTabbedPane1.addTab("Pesquisar", jPanel2);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 51, 153));
        jLabel1.setText("CADASTRO ENTREGADORES");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 349, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(222, 222, 222))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTabbedPane1))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField12ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField12ActionPerformed

    private void jButtonCadastrarEntregadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCadastrarEntregadorActionPerformed
        EntregadorModel obj = new EntregadorModel(); // TODO add your handling code here:
        obj.setCodigo(Integer.parseInt(jTextFieldCodigo.getText()));
        obj.setNome(jTextFieldNome.getText());
        obj.setCelular(jFormattedTextFieldCelular.getText());
        obj.setData(jFormattedTextFieldData.getText());
        EntregadorDAO dao = new EntregadorDAO();
        dao.cadastrarEntregador(obj);
        
        new Utilitarios().LimpaTela(jPanelCadastro);
    }//GEN-LAST:event_jButtonCadastrarEntregadorActionPerformed

    private void jButtonAtualizarEntregadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAtualizarEntregadorActionPerformed
        EntregadorModel obj = new EntregadorModel(); 
        obj.setCodigo(Integer.parseInt(jTextFieldCodigo.getText()));
        obj.setNome(jTextFieldNome.getText());
        obj.setCelular(jFormattedTextFieldCelular.getText());
        obj.setData(jFormattedTextFieldData.getText());
        EntregadorDAO dao = new EntregadorDAO();
        dao.atualizarEntregador(obj);
        
        new Utilitarios().LimpaTela(jPanelCadastro);
    }//GEN-LAST:event_jButtonAtualizarEntregadorActionPerformed

    private void jButtonApagarEntregadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonApagarEntregadorActionPerformed
        new Utilitarios().LimpaTela(jPanelCadastro);
    }//GEN-LAST:event_jButtonApagarEntregadorActionPerformed

    private void jButtonExcluirEntregadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonExcluirEntregadorActionPerformed
        EntregadorModel obj = new EntregadorModel();
        obj.setCodigo(Integer.parseInt(jTextFieldCodigo.getText()));
        
        EntregadorDAO dao = new EntregadorDAO();
        dao.excluirEntregador(obj);
         new Utilitarios().LimpaTela(jPanelCadastro);
    }//GEN-LAST:event_jButtonExcluirEntregadorActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        listar();
        //events - window - WindowActivated
    }//GEN-LAST:event_formWindowActivated

    private void jButtonExcluirFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonExcluirFuncionarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonExcluirFuncionarioActionPerformed

    private void jTabbedPane1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTabbedPane1MouseClicked
       //jTabbedPane1.setSelectedIndex(0);
       jTextFieldCodigo.setText(jTablePesquisar.getValueAt(jTablePesquisar.getSelectedRow(),0).toString());
       jTextFieldNome.setText(jTablePesquisar.getValueAt(jTablePesquisar.getSelectedRow(),1).toString());
       jFormattedTextFieldCelular.setText(jTablePesquisar.getValueAt(jTablePesquisar.getSelectedRow(),2).toString());
       jFormattedTextFieldData.setText(jTablePesquisar.getValueAt(jTablePesquisar.getSelectedRow(),3).toString());
       
// TODO add your handling code here:
    }//GEN-LAST:event_jTabbedPane1MouseClicked

    private void jButtonPesquisarEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPesquisarEditarActionPerformed

        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonPesquisarEditarActionPerformed

    private void jButtonPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPesquisarActionPerformed
        String nome = "%"+jTextFieldPesquisarNome.getText()+"%";
        EntregadorDAO dao = new EntregadorDAO();
        List<EntregadorModel> lista = dao.buscaEntregadorNome(nome);
        DefaultTableModel dados = (DefaultTableModel)jTablePesquisar.getModel();
        dados.setNumRows(0) ;
        
        for(EntregadorModel c : lista){
            dados.addRow(new Object[]{
            c.getCodigo(),
            c.getNome(),
            c.getCelular(),
            c.getData()
            });
        }
    }//GEN-LAST:event_jButtonPesquisarActionPerformed

    private void jTextFieldPesquisarNomeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldPesquisarNomeKeyPressed
        String nome = "%"+jTextFieldPesquisarNome.getText()+"%";
        EntregadorDAO dao = new EntregadorDAO();
        List<EntregadorModel> lista = dao.buscaEntregadorNome(nome);
        DefaultTableModel dados = (DefaultTableModel)jTablePesquisar.getModel();
        dados.setNumRows(0) ;
        
        for(EntregadorModel c : lista){
            dados.addRow(new Object[]{
           c.getCodigo(),
            c.getNome(),
            c.getCelular(),
            c.getData()
            });
        }
    }//GEN-LAST:event_jTextFieldPesquisarNomeKeyPressed

    private void jTextFieldCodigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldCodigoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldCodigoActionPerformed

    private void jTextFieldNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldNomeActionPerformed

    private void jFormattedTextFieldCelularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFormattedTextFieldCelularActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jFormattedTextFieldCelularActionPerformed

    private void jButtonPesquisarEntregadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPesquisarEntregadorActionPerformed
       try {
            int cod = Integer.parseInt(jTextFieldCodigo.getText());
            EntregadorModel obj = new EntregadorModel();
            EntregadorDAO dao = new EntregadorDAO();
            obj = dao.consultaPorCodigo(cod);
            
       jTextFieldCodigo.setText(String.valueOf(obj.getCodigo()));
       jTextFieldNome.setText(obj.getNome());
       jFormattedTextFieldCelular.setText(obj.getCelular());
       jFormattedTextFieldData.setText(obj.getData());
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null,"Erro ao mostrar os dados na tela cadastro."+e);
     
        }
    }//GEN-LAST:event_jButtonPesquisarEntregadorActionPerformed
 

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroEntregador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroEntregador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroEntregador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroEntregador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaCadastroEntregador().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonApagarEntregador;
    private javax.swing.JButton jButtonAtualizarEntregador;
    private javax.swing.JButton jButtonCadastrarEntregador;
    private javax.swing.JButton jButtonExcluirEntregador;
    private javax.swing.JButton jButtonExcluirFuncionario;
    private javax.swing.JButton jButtonNovo;
    private javax.swing.JButton jButtonPesquisar;
    private javax.swing.JButton jButtonPesquisarEditar;
    private javax.swing.JButton jButtonPesquisarEntregador;
    private javax.swing.JButton jButtonPesquisarSalvar;
    private javax.swing.JFormattedTextField jFormattedTextFieldCelular;
    private javax.swing.JFormattedTextField jFormattedTextFieldData;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel54;
    private javax.swing.JLabel jLabel56;
    private javax.swing.JLabel jLabel57;
    private javax.swing.JLabel jLabel63;
    private javax.swing.JLabel jLabelNomePesquisar;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanelCadastro;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTablePesquisar;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField12;
    private javax.swing.JTextField jTextFieldCodigo;
    private javax.swing.JTextField jTextFieldNome;
    private javax.swing.JTextField jTextFieldPesquisarNome;
    // End of variables declaration//GEN-END:variables
}
