/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import dao.FuncionarioDAO;
import java.awt.event.KeyEvent;
import java.sql.SQLException;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.FuncionarioModel;


import javax.swing.table.DefaultTableModel;
import model.Utilitarios;
/**
 *
 * @author Rosany
 */
public class TelaCadastroFuncionario extends javax.swing.JFrame {
    
    public void listar(){
        FuncionarioDAO dao = new FuncionarioDAO();
        List<FuncionarioModel> lista = dao.listarFuncionario();
        DefaultTableModel dados = (DefaultTableModel)jTablePesquisarFuncionario.getModel();
        dados.setNumRows(0) ;
        
        for(FuncionarioModel c : lista){
            dados.addRow(new Object[]{
            c.getCodigo(),
            c.getNome(),
            c.getNascimento(),
            c.getSexo(),
            c.getRg(),
            c.getCor(),
            c.getCpf(),
            c.getEmail(),
            c.getEndereco(),
            c.getNumero(),
            c.getRua(),
            c.getCep(),
            c.getCidade(),
            c.getBairro(),
            c.getUf(),
            c.getNaturalidade(),
            c.getTelefone(),
            c.getCelular(),
            c.getEspecial(),
            c.getEspecificar(),
            c.getPai(),
            c.getMae(),
            c.getCargo(),
            c.getData(),
            c.getSenha()      
            });
        }
        
    }

    /**
     * Creates new form TelaCadastroCliente
     */
    public TelaCadastroFuncionario() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel13 = new javax.swing.JLabel();
        jTextField12 = new javax.swing.JTextField();
        jTextField1 = new javax.swing.JTextField();
        jTabbedPaneCadastro = new javax.swing.JTabbedPane();
        jPanelCadastro = new javax.swing.JPanel();
        jButtonCadastrarFuncionario = new javax.swing.JButton();
        jButtonAtualizarFuncionario = new javax.swing.JButton();
        jButtonPesquisarFuncionario = new javax.swing.JButton();
        jButtonExcluirFuncionario = new javax.swing.JButton();
        jLabel84 = new javax.swing.JLabel();
        jLabel85 = new javax.swing.JLabel();
        jTextFieldCargo = new javax.swing.JTextField();
        jLabel86 = new javax.swing.JLabel();
        jLabel71 = new javax.swing.JLabel();
        jTextFieldCodigo = new javax.swing.JTextField();
        jLabel87 = new javax.swing.JLabel();
        jTextFieldNome = new javax.swing.JTextField();
        jFormattedTextFieldNascimento = new javax.swing.JFormattedTextField();
        jLabel88 = new javax.swing.JLabel();
        jLabel89 = new javax.swing.JLabel();
        jLabel90 = new javax.swing.JLabel();
        jLabel72 = new javax.swing.JLabel();
        jLabel73 = new javax.swing.JLabel();
        jTextFieldBairro = new javax.swing.JTextField();
        jTextFieldEndereco = new javax.swing.JTextField();
        jTextFieldCidade = new javax.swing.JTextField();
        jLabel74 = new javax.swing.JLabel();
        jLabel75 = new javax.swing.JLabel();
        jLabel76 = new javax.swing.JLabel();
        jLabel91 = new javax.swing.JLabel();
        jLabel77 = new javax.swing.JLabel();
        jTextFieldEspecificar = new javax.swing.JTextField();
        jLabel92 = new javax.swing.JLabel();
        jTextFieldPai = new javax.swing.JTextField();
        jLabel93 = new javax.swing.JLabel();
        jTextFieldMae = new javax.swing.JTextField();
        jLabel78 = new javax.swing.JLabel();
        jTextFieldEmail = new javax.swing.JTextField();
        jTextFieldRua = new javax.swing.JTextField();
        jFormattedTextFieldRg = new javax.swing.JFormattedTextField();
        jFormattedTextFieldData = new javax.swing.JFormattedTextField();
        jFormattedTextFieldCpf = new javax.swing.JFormattedTextField();
        jFormattedTextFieldTelefone = new javax.swing.JFormattedTextField();
        jFormattedTextFieldCelular = new javax.swing.JFormattedTextField();
        jTextFieldNumero = new javax.swing.JTextField();
        jFormattedTextFieldCep = new javax.swing.JFormattedTextField();
        jLabel79 = new javax.swing.JLabel();
        jLabel80 = new javax.swing.JLabel();
        jTextFieldNaturalidade = new javax.swing.JTextField();
        jLabel81 = new javax.swing.JLabel();
        jLabel82 = new javax.swing.JLabel();
        jLabel83 = new javax.swing.JLabel();
        jLabel94 = new javax.swing.JLabel();
        jTextFieldUf = new javax.swing.JTextField();
        jButtonApagarFuncionario1 = new javax.swing.JButton();
        jComboBoxCor = new javax.swing.JComboBox<>();
        jComboBoxSexo = new javax.swing.JComboBox<>();
        jComboBoxEspecial = new javax.swing.JComboBox<>();
        jPasswordFieldSenha = new javax.swing.JPasswordField();
        jLabel95 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabelNomePesquisar = new javax.swing.JLabel();
        jTextFieldPesquisarNome = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTablePesquisarFuncionario = new javax.swing.JTable();
        jButtonNovo = new javax.swing.JButton();
        jButtonPesquisarSalvar = new javax.swing.JButton();
        jButtonPesquisarEditar = new javax.swing.JButton();
        jButtonExcluirCliente = new javax.swing.JButton();
        jButtonPesquisar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        jLabel13.setText("UF:");

        jTextField12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField12ActionPerformed(evt);
            }
        });

        jTextField1.setText("jTextField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setAutoRequestFocus(false);
        setBackground(new java.awt.Color(255, 153, 153));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        jTabbedPaneCadastro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTabbedPaneCadastroMouseClicked(evt);
            }
        });

        jButtonCadastrarFuncionario.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButtonCadastrarFuncionario.setForeground(new java.awt.Color(0, 0, 153));
        jButtonCadastrarFuncionario.setText("SALVAR");
        jButtonCadastrarFuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCadastrarFuncionarioActionPerformed(evt);
            }
        });

        jButtonAtualizarFuncionario.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButtonAtualizarFuncionario.setForeground(new java.awt.Color(0, 0, 153));
        jButtonAtualizarFuncionario.setText("ATUALIZAR");
        jButtonAtualizarFuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAtualizarFuncionarioActionPerformed(evt);
            }
        });

        jButtonPesquisarFuncionario.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButtonPesquisarFuncionario.setForeground(new java.awt.Color(0, 0, 153));
        jButtonPesquisarFuncionario.setText("PESQUISAR");
        jButtonPesquisarFuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPesquisarFuncionarioActionPerformed(evt);
            }
        });

        jButtonExcluirFuncionario.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButtonExcluirFuncionario.setForeground(new java.awt.Color(0, 0, 153));
        jButtonExcluirFuncionario.setText("EXCLUIR");
        jButtonExcluirFuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonExcluirFuncionarioActionPerformed(evt);
            }
        });

        jLabel84.setText("RG:");

        jLabel85.setText("Especificar:");

        jLabel86.setText("Código:");

        jLabel71.setText("Data:");

        jTextFieldCodigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldCodigoActionPerformed(evt);
            }
        });

        jLabel87.setText("Nome do Funcionário:");

        jTextFieldNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldNomeActionPerformed(evt);
            }
        });

        try {
            jFormattedTextFieldNascimento.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        jLabel88.setText("Data de Nascimento:");

        jLabel89.setText("Cor/Raça");

        jLabel90.setText("Sexo:");

        jLabel72.setText("CEP:");

        jLabel73.setText("Bairro:");

        jTextFieldEndereco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldEnderecoActionPerformed(evt);
            }
        });

        jLabel74.setText("Endereço:");

        jLabel75.setText("Nº:");

        jLabel76.setText("Cidade:");

        jLabel91.setText("Portador de Nec. Especial");

        jLabel77.setText("E-mail:");

        jLabel92.setText("Nome do PAI:");

        jLabel93.setText("Nome do MÃE:");

        jLabel78.setText("Rua:");

        try {
            jFormattedTextFieldRg.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("#.###.###")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        try {
            jFormattedTextFieldData.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jFormattedTextFieldData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFormattedTextFieldDataActionPerformed(evt);
            }
        });

        try {
            jFormattedTextFieldCpf.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        try {
            jFormattedTextFieldTelefone.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##)####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        try {
            jFormattedTextFieldCelular.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##)# ####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jFormattedTextFieldCelular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFormattedTextFieldCelularActionPerformed(evt);
            }
        });

        try {
            jFormattedTextFieldCep.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##.###-###")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jFormattedTextFieldCep.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jFormattedTextFieldCepKeyPressed(evt);
            }
        });

        jLabel79.setText("Cargo:");

        jLabel80.setText("Naturalidade:");

        jLabel81.setText("Telefone:");

        jLabel82.setText("Celular:");

        jLabel83.setText("CPF:");

        jLabel94.setText("UF:");

        jButtonApagarFuncionario1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButtonApagarFuncionario1.setForeground(new java.awt.Color(0, 0, 153));
        jButtonApagarFuncionario1.setText("APAGAR");
        jButtonApagarFuncionario1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonApagarFuncionario1ActionPerformed(evt);
            }
        });

        jComboBoxCor.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Branca", "Preta", "Parda", "Indígena", "Amarela" }));

        jComboBoxSexo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Feminino", "Masculino", "Outros", "Prefiro Não Informar" }));

        jComboBoxEspecial.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Sim", "Não" }));

        jPasswordFieldSenha.setText("jPasswordField1");

        jLabel95.setText("Senha:");

        javax.swing.GroupLayout jPanelCadastroLayout = new javax.swing.GroupLayout(jPanelCadastro);
        jPanelCadastro.setLayout(jPanelCadastroLayout);
        jPanelCadastroLayout.setHorizontalGroup(
            jPanelCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCadastroLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelCadastroLayout.createSequentialGroup()
                        .addComponent(jLabel79)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldCargo, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(105, 105, 105)
                        .addComponent(jLabel71)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jFormattedTextFieldData, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelCadastroLayout.createSequentialGroup()
                        .addComponent(jLabel86)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonPesquisarFuncionario)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanelCadastroLayout.createSequentialGroup()
                .addGroup(jPanelCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelCadastroLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanelCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelCadastroLayout.createSequentialGroup()
                                .addGroup(jPanelCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanelCadastroLayout.createSequentialGroup()
                                        .addComponent(jLabel74)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jTextFieldEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel75))
                                    .addGroup(jPanelCadastroLayout.createSequentialGroup()
                                        .addComponent(jLabel89)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jComboBoxCor, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel83)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanelCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanelCadastroLayout.createSequentialGroup()
                                        .addComponent(jTextFieldNumero, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLabel78)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jTextFieldRua, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addGroup(jPanelCadastroLayout.createSequentialGroup()
                                        .addComponent(jFormattedTextFieldCpf, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel77)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jTextFieldEmail))))
                            .addGroup(jPanelCadastroLayout.createSequentialGroup()
                                .addGroup(jPanelCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanelCadastroLayout.createSequentialGroup()
                                        .addGap(1, 1, 1)
                                        .addComponent(jLabel92)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jTextFieldPai, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLabel93)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jTextFieldMae, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanelCadastroLayout.createSequentialGroup()
                                        .addComponent(jLabel88)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jFormattedTextFieldNascimento, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel90)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jComboBoxSexo, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel84)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jFormattedTextFieldRg, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanelCadastroLayout.createSequentialGroup()
                                        .addGroup(jPanelCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanelCadastroLayout.createSequentialGroup()
                                                .addComponent(jLabel72)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jFormattedTextFieldCep, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(jPanelCadastroLayout.createSequentialGroup()
                                                .addComponent(jLabel94)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(jTextFieldUf, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGap(12, 12, 12)
                                        .addGroup(jPanelCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanelCadastroLayout.createSequentialGroup()
                                                .addComponent(jLabel80)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jTextFieldNaturalidade, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(jPanelCadastroLayout.createSequentialGroup()
                                                .addComponent(jLabel76)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jTextFieldCidade, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jLabel73)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(jTextFieldBairro, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                    .addGroup(jPanelCadastroLayout.createSequentialGroup()
                                        .addComponent(jLabel81)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jFormattedTextFieldTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLabel82)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jFormattedTextFieldCelular, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(47, 47, 47)
                                        .addComponent(jLabel95)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jPasswordFieldSenha))
                                    .addGroup(jPanelCadastroLayout.createSequentialGroup()
                                        .addComponent(jLabel91)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jComboBoxEspecial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(54, 54, 54)
                                        .addComponent(jLabel85)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jTextFieldEspecificar)))
                                .addGap(0, 77, Short.MAX_VALUE))))
                    .addGroup(jPanelCadastroLayout.createSequentialGroup()
                        .addGroup(jPanelCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelCadastroLayout.createSequentialGroup()
                                .addGap(100, 100, 100)
                                .addComponent(jButtonCadastrarFuncionario)
                                .addGap(18, 18, 18)
                                .addComponent(jButtonAtualizarFuncionario)
                                .addGap(24, 24, 24)
                                .addComponent(jButtonApagarFuncionario1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButtonExcluirFuncionario))
                            .addGroup(jPanelCadastroLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel87)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldNome, javax.swing.GroupLayout.PREFERRED_SIZE, 352, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanelCadastroLayout.setVerticalGroup(
            jPanelCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelCadastroLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanelCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel86)
                    .addComponent(jTextFieldCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonPesquisarFuncionario))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel87)
                    .addComponent(jTextFieldNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jFormattedTextFieldNascimento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel88)
                    .addComponent(jLabel90)
                    .addComponent(jLabel84)
                    .addComponent(jFormattedTextFieldRg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBoxSexo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel89)
                        .addComponent(jFormattedTextFieldCpf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel77)
                        .addComponent(jTextFieldEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jComboBoxCor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel83, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel74)
                    .addComponent(jTextFieldEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel75)
                    .addComponent(jTextFieldNumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel78)
                    .addComponent(jTextFieldRua, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel72)
                    .addComponent(jFormattedTextFieldCep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel76)
                    .addComponent(jTextFieldCidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel73)
                    .addComponent(jTextFieldBairro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel80)
                    .addComponent(jTextFieldNaturalidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel94)
                    .addComponent(jTextFieldUf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel81)
                    .addComponent(jLabel82)
                    .addComponent(jFormattedTextFieldTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jFormattedTextFieldCelular, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPasswordFieldSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel95))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel91)
                    .addComponent(jLabel85)
                    .addComponent(jTextFieldEspecificar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBoxEspecial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel92)
                    .addComponent(jTextFieldPai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel93)
                    .addComponent(jTextFieldMae, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel71)
                    .addComponent(jFormattedTextFieldData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel79)
                    .addComponent(jTextFieldCargo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonCadastrarFuncionario)
                    .addComponent(jButtonAtualizarFuncionario)
                    .addComponent(jButtonExcluirFuncionario)
                    .addComponent(jButtonApagarFuncionario1))
                .addContainerGap(145, Short.MAX_VALUE))
        );

        jTabbedPaneCadastro.addTab("Cadastro", jPanelCadastro);

        jLabelNomePesquisar.setText("Nome:");

        jTextFieldPesquisarNome.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextFieldPesquisarNomeKeyPressed(evt);
            }
        });

        jTablePesquisarFuncionario.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Codigo", "Nome", "Data Nasc.", "Sexo", "RG", "Cor", "CPF", "Email", "Endereço", "Número", "Rua", "CEP", "Cidade", "Bairro", "UF", "Naturalidade", "Telefone", "Celular", "Port. Espcecial", "Especificar", "Pai", "Mãe", "Cargo", "Data", "Senha"
            }
        ));
        jScrollPane1.setViewportView(jTablePesquisarFuncionario);

        jButtonNovo.setText("Novo");

        jButtonPesquisarSalvar.setText("Salvar");

        jButtonPesquisarEditar.setText("Editar");
        jButtonPesquisarEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPesquisarEditarActionPerformed(evt);
            }
        });

        jButtonExcluirCliente.setText("Excluir");
        jButtonExcluirCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonExcluirClienteActionPerformed(evt);
            }
        });

        jButtonPesquisar.setText("Pesquisar");
        jButtonPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPesquisarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(129, 129, 129)
                                .addComponent(jButtonNovo)
                                .addGap(18, 18, 18)
                                .addComponent(jButtonPesquisarSalvar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButtonPesquisarEditar)
                                .addGap(18, 18, 18)
                                .addComponent(jButtonExcluirCliente))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabelNomePesquisar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldPesquisarNome, javax.swing.GroupLayout.PREFERRED_SIZE, 331, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jButtonPesquisar)))
                        .addGap(0, 234, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelNomePesquisar)
                    .addComponent(jTextFieldPesquisarNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonPesquisar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 378, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonNovo)
                    .addComponent(jButtonPesquisarSalvar)
                    .addComponent(jButtonPesquisarEditar)
                    .addComponent(jButtonExcluirCliente))
                .addGap(9, 9, 9))
        );

        jTabbedPaneCadastro.addTab("Pesquisar", jPanel2);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 51, 153));
        jLabel1.setText("CADASTRAR FUNCIONÁRIOS");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPaneCadastro)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 571, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPaneCadastro))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField12ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField12ActionPerformed

    private void jButtonCadastrarFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCadastrarFuncionarioActionPerformed
        FuncionarioModel obj = new FuncionarioModel(); // TODO add your handling code here:
        obj.setCodigo(Integer.parseInt(jTextFieldCodigo.getText()));
        obj.setNome(jTextFieldNome.getText());
        obj.setNascimento(jFormattedTextFieldNascimento.getText());
        obj.setSexo(jComboBoxSexo.getSelectedItem().toString());
        obj.setRg(jFormattedTextFieldRg.getText());
        obj.setCor(jComboBoxCor.getSelectedItem().toString());
        obj.setCpf(jFormattedTextFieldCpf.getText());
        obj.setEmail(jTextFieldEmail.getText());
        obj.setEndereco(jTextFieldEndereco.getText());
        obj.setNumero(Integer.parseInt(jTextFieldNumero.getText()));
        obj.setRua(jTextFieldRua.getText());
        obj.setCep(jFormattedTextFieldCep.getText());
        obj.setCidade(jTextFieldCidade.getText());
        obj.setBairro(jTextFieldBairro.getText());
        obj.setUf(jTextFieldUf.getText());
        obj.setNaturalidade(jTextFieldNaturalidade.getText());
        obj.setTelefone(jFormattedTextFieldTelefone.getText());
        obj.setCelular(jFormattedTextFieldCelular.getText());
        obj.setEspecial(jComboBoxEspecial.getSelectedItem().toString());
        obj.setEspecificar(jTextFieldEspecificar.getText());
        obj.setPai(jTextFieldPai.getText());
        obj.setMae(jTextFieldMae.getText());
        obj.setCargo(jTextFieldCargo.getText());
        obj.setData(jFormattedTextFieldData.getText());
        obj.setSenha(jPasswordFieldSenha.getText());
        FuncionarioDAO dao = new FuncionarioDAO();
        dao.cadastrarFuncionario(obj);
        
        new Utilitarios().LimpaTela(jPanelCadastro);
    }//GEN-LAST:event_jButtonCadastrarFuncionarioActionPerformed

    private void jButtonAtualizarFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAtualizarFuncionarioActionPerformed
        FuncionarioModel obj = new FuncionarioModel(); 
        obj.setCodigo(Integer.parseInt(jTextFieldCodigo.getText()));
        obj.setNome(jTextFieldNome.getText());
        obj.setNascimento(jFormattedTextFieldNascimento.getText());
        obj.setSexo(jComboBoxSexo.getSelectedItem().toString());
        obj.setRg(jFormattedTextFieldRg.getText());
        obj.setCor(jComboBoxCor.getSelectedItem().toString());
        obj.setCpf(jFormattedTextFieldCpf.getText());
        obj.setEmail(jTextFieldEmail.getText());
        obj.setEndereco(jTextFieldEndereco.getText());
        obj.setNumero(Integer.parseInt(jTextFieldNumero.getText()));
        obj.setRua(jTextFieldRua.getText());
        obj.setCep(jFormattedTextFieldCep.getText());
        obj.setCidade(jTextFieldCidade.getText());
        obj.setBairro(jTextFieldBairro.getText());
        obj.setUf(jTextFieldUf.getText());
        obj.setNaturalidade(jTextFieldNaturalidade.getText());
        obj.setTelefone(jFormattedTextFieldTelefone.getText());
        obj.setCelular(jFormattedTextFieldCelular.getText());
        obj.setEspecial(jComboBoxEspecial.getSelectedItem().toString());
        obj.setEspecificar(jTextFieldEspecificar.getText());
        obj.setPai(jTextFieldPai.getText());
        obj.setMae(jTextFieldMae.getText());
        obj.setCargo(jTextFieldCargo.getText());
        obj.setData(jFormattedTextFieldData.getText());
        obj.setSenha(jPasswordFieldSenha.getText());
        
        FuncionarioDAO dao = new FuncionarioDAO();
        dao.atualizarFuncionario(obj);
        
        new Utilitarios().LimpaTela(jPanelCadastro);
    }//GEN-LAST:event_jButtonAtualizarFuncionarioActionPerformed

    private void jButtonPesquisarFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPesquisarFuncionarioActionPerformed
         try {
            int codigo_func = Integer.parseInt(jTextFieldCodigo.getText());
            FuncionarioModel obj = new FuncionarioModel();
            FuncionarioDAO dao = new FuncionarioDAO();
            obj = dao.consultaPorCodigo(codigo_func);
            
       jTextFieldCodigo.setText(String.valueOf(obj.getCodigo()));
       jTextFieldNome.setText(obj.getNome());
       jFormattedTextFieldNascimento.setText(obj.getNascimento());
       jComboBoxSexo.setSelectedItem(obj.getSexo());
       jFormattedTextFieldRg.setText(obj.getRg());
       jComboBoxCor.setSelectedItem(obj.getCor());
       jFormattedTextFieldCpf.setText(obj.getCpf());
       jTextFieldEmail.setText(obj.getEmail());
       jTextFieldEndereco.setText(obj.getEndereco());
       jTextFieldNumero.setText(String.valueOf(obj.getNumero()));
       jTextFieldRua.setText(obj.getRua());
       jFormattedTextFieldCep.setText(obj.getCep());
       jTextFieldCidade.setText(obj.getCidade());
       jTextFieldBairro.setText(obj.getBairro());
       jTextFieldUf.setText(obj.getUf());
       jTextFieldNaturalidade.setText(obj.getNaturalidade());
       jFormattedTextFieldTelefone.setText(obj.getTelefone());
       jFormattedTextFieldCelular.setText(obj.getCelular());
       jComboBoxEspecial.setSelectedItem(obj.getEspecial());
       jTextFieldEspecificar.setText(obj.getEspecificar());
       jTextFieldPai.setText(obj.getPai());
       jTextFieldMae.setText(obj.getMae());
       jTextFieldCargo.setText(obj.getCargo());
       jFormattedTextFieldData.setText(obj.getData());
       jPasswordFieldSenha.setText(obj.getSenha());
       
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null,"Erro ao mostrar os dados na tela cadastro."+e);
     
        }
    }//GEN-LAST:event_jButtonPesquisarFuncionarioActionPerformed

    private void jButtonExcluirFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonExcluirFuncionarioActionPerformed
        FuncionarioModel obj = new FuncionarioModel();
        obj.setCodigo(Integer.parseInt(jTextFieldCodigo.getText()));
        
        FuncionarioDAO dao = new FuncionarioDAO();
        dao.excluirFuncionario(obj);
        
        new Utilitarios().LimpaTela(jPanelCadastro);        
    }//GEN-LAST:event_jButtonExcluirFuncionarioActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        listar();
        //events - window - WindowActivated
    }//GEN-LAST:event_formWindowActivated

    private void jButtonExcluirClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonExcluirClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonExcluirClienteActionPerformed

    private void jTabbedPaneCadastroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTabbedPaneCadastroMouseClicked
       jTextFieldCodigo.setText(jTablePesquisarFuncionario.getValueAt(jTablePesquisarFuncionario.getSelectedRow(),0).toString());
       jTextFieldNome.setText(jTablePesquisarFuncionario.getValueAt(jTablePesquisarFuncionario.getSelectedRow(),1).toString());
       jFormattedTextFieldNascimento.setText(jTablePesquisarFuncionario.getValueAt(jTablePesquisarFuncionario.getSelectedRow(),2).toString());
       jComboBoxSexo.setSelectedItem(jTablePesquisarFuncionario.getValueAt(jTablePesquisarFuncionario.getSelectedRow(),3).toString());
       jFormattedTextFieldRg.setText(jTablePesquisarFuncionario.getValueAt(jTablePesquisarFuncionario.getSelectedRow(),4).toString());
       jComboBoxCor.setSelectedItem(jTablePesquisarFuncionario.getValueAt(jTablePesquisarFuncionario.getSelectedRow(),5).toString());
       jFormattedTextFieldCpf.setText(jTablePesquisarFuncionario.getValueAt(jTablePesquisarFuncionario.getSelectedRow(),6).toString());
       jTextFieldEmail.setText(jTablePesquisarFuncionario.getValueAt(jTablePesquisarFuncionario.getSelectedRow(),7).toString());
       jTextFieldEndereco.setText(jTablePesquisarFuncionario.getValueAt(jTablePesquisarFuncionario.getSelectedRow(),8).toString());
       jTextFieldNumero.setText(jTablePesquisarFuncionario.getValueAt(jTablePesquisarFuncionario.getSelectedRow(),9).toString());
       jTextFieldRua.setText(jTablePesquisarFuncionario.getValueAt(jTablePesquisarFuncionario.getSelectedRow(),10).toString());
       jFormattedTextFieldCep.setText(jTablePesquisarFuncionario.getValueAt(jTablePesquisarFuncionario.getSelectedRow(),11).toString());
       jTextFieldCidade.setText(jTablePesquisarFuncionario.getValueAt(jTablePesquisarFuncionario.getSelectedRow(),12).toString());
       jTextFieldBairro.setText(jTablePesquisarFuncionario.getValueAt(jTablePesquisarFuncionario.getSelectedRow(),13).toString());
       jTextFieldUf.setText(jTablePesquisarFuncionario.getValueAt(jTablePesquisarFuncionario.getSelectedRow(),14).toString());
       jTextFieldNaturalidade.setText(jTablePesquisarFuncionario.getValueAt(jTablePesquisarFuncionario.getSelectedRow(),15).toString());
       jFormattedTextFieldTelefone.setText(jTablePesquisarFuncionario.getValueAt(jTablePesquisarFuncionario.getSelectedRow(),16).toString());
       jFormattedTextFieldCelular.setText(jTablePesquisarFuncionario.getValueAt(jTablePesquisarFuncionario.getSelectedRow(),17).toString());
       jComboBoxEspecial.setSelectedItem(jTablePesquisarFuncionario.getValueAt(jTablePesquisarFuncionario.getSelectedRow(),18).toString());
       jTextFieldEspecificar.setText(jTablePesquisarFuncionario.getValueAt(jTablePesquisarFuncionario.getSelectedRow(),19).toString());
       jTextFieldPai.setText(jTablePesquisarFuncionario.getValueAt(jTablePesquisarFuncionario.getSelectedRow(),20).toString());
       jTextFieldMae.setText(jTablePesquisarFuncionario.getValueAt(jTablePesquisarFuncionario.getSelectedRow(),21).toString());
       jTextFieldCargo.setText(jTablePesquisarFuncionario.getValueAt(jTablePesquisarFuncionario.getSelectedRow(),22).toString());
       jFormattedTextFieldData.setText(jTablePesquisarFuncionario.getValueAt(jTablePesquisarFuncionario.getSelectedRow(),23).toString());
       jPasswordFieldSenha.setText(jTablePesquisarFuncionario.getValueAt(jTablePesquisarFuncionario.getSelectedRow(),24).toString());
       
// TODO add your handling code here:
    }//GEN-LAST:event_jTabbedPaneCadastroMouseClicked

    private void jButtonPesquisarEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPesquisarEditarActionPerformed

        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonPesquisarEditarActionPerformed

    private void jButtonPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPesquisarActionPerformed
        String nome = "%"+jTextFieldPesquisarNome.getText()+"%";
        FuncionarioDAO dao = new FuncionarioDAO();
        List<FuncionarioModel> lista = dao.buscaFuncionarioNome(nome);
        DefaultTableModel dados = (DefaultTableModel)jTablePesquisarFuncionario.getModel();
        dados.setNumRows(0) ;
        
        for(FuncionarioModel c : lista){
            dados.addRow(new Object[]{
            c.getCodigo(),
            c.getNome(),
            c.getNascimento(),
            c.getSexo(),
            c.getRg(),
            c.getCor(),
            c.getCpf(),
            c.getEmail(),
            c.getEndereco(),
            c.getNumero(),
            c.getRua(),
            c.getCep(),
            c.getCidade(),
            c.getBairro(),
            c.getUf(),
            c.getNaturalidade(),
            c.getTelefone(),
            c.getCelular(),
            c.getEspecial(),
            c.getEspecificar(),
            c.getPai(),
            c.getMae(),
            c.getCargo(),
            c.getData(),
            c.getSenha()
            });
        }
    }//GEN-LAST:event_jButtonPesquisarActionPerformed

    private void jTextFieldPesquisarNomeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldPesquisarNomeKeyPressed
        String nome = "%"+jTextFieldPesquisarNome.getText()+"%";
        FuncionarioDAO dao = new FuncionarioDAO();
        List<FuncionarioModel> lista = dao.buscaFuncionarioNome(nome);
        DefaultTableModel dados = (DefaultTableModel)jTablePesquisarFuncionario.getModel();
        dados.setNumRows(0) ;
        
        for(FuncionarioModel c : lista){
            dados.addRow(new Object[]{
            c.getCodigo(),
            c.getNome(),
            c.getNascimento(),
            c.getSexo(),
            c.getRg(),
            c.getCor(),
            c.getCpf(),
            c.getEmail(),
            c.getEndereco(),
            c.getNumero(),
            c.getRua(),
            c.getCep(),
            c.getCidade(),
            c.getBairro(),
            c.getUf(),
            c.getNaturalidade(),
            c.getTelefone(),
            c.getCelular(),
            c.getEspecial(),
            c.getEspecificar(),
            c.getPai(),
            c.getMae(),
            c.getCargo(),
            c.getData(),
            c.getSenha()
            });
        }
    }//GEN-LAST:event_jTextFieldPesquisarNomeKeyPressed

    private void jTextFieldCodigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldCodigoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldCodigoActionPerformed

    private void jTextFieldNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldNomeActionPerformed

    private void jTextFieldEnderecoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldEnderecoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldEnderecoActionPerformed

    private void jFormattedTextFieldDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFormattedTextFieldDataActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jFormattedTextFieldDataActionPerformed

    private void jFormattedTextFieldCelularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFormattedTextFieldCelularActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jFormattedTextFieldCelularActionPerformed

    private void jButtonApagarFuncionario1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonApagarFuncionario1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonApagarFuncionario1ActionPerformed

    private void jFormattedTextFieldCepKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jFormattedTextFieldCepKeyPressed
      //Programacao do keypress
	if (evt.getKeyCode() == KeyEvent.VK_ENTER) { 
         FuncionarioModel obj =  new FuncionarioModel();
         FuncionarioDAO dao = new FuncionarioDAO();
         obj = dao.buscaCep(jFormattedTextFieldCep.getText());
         
         jTextFieldEndereco.setText(obj.getEndereco());
         jTextFieldBairro.setText(obj.getBairro());
         jTextFieldCidade.setText(obj.getCidade());
         jTextFieldUf.setText(obj.getUf());            
        // System.out.println(obj.getUf());;
         
     }
    }//GEN-LAST:event_jFormattedTextFieldCepKeyPressed
 

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaCadastroFuncionario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonApagarFuncionario1;
    private javax.swing.JButton jButtonAtualizarFuncionario;
    private javax.swing.JButton jButtonCadastrarFuncionario;
    private javax.swing.JButton jButtonExcluirCliente;
    private javax.swing.JButton jButtonExcluirFuncionario;
    private javax.swing.JButton jButtonNovo;
    private javax.swing.JButton jButtonPesquisar;
    private javax.swing.JButton jButtonPesquisarEditar;
    private javax.swing.JButton jButtonPesquisarFuncionario;
    private javax.swing.JButton jButtonPesquisarSalvar;
    private javax.swing.JComboBox<String> jComboBoxCor;
    private javax.swing.JComboBox<String> jComboBoxEspecial;
    private javax.swing.JComboBox<String> jComboBoxSexo;
    private javax.swing.JFormattedTextField jFormattedTextFieldCelular;
    private javax.swing.JFormattedTextField jFormattedTextFieldCep;
    private javax.swing.JFormattedTextField jFormattedTextFieldCpf;
    private javax.swing.JFormattedTextField jFormattedTextFieldData;
    private javax.swing.JFormattedTextField jFormattedTextFieldNascimento;
    private javax.swing.JFormattedTextField jFormattedTextFieldRg;
    private javax.swing.JFormattedTextField jFormattedTextFieldTelefone;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel71;
    private javax.swing.JLabel jLabel72;
    private javax.swing.JLabel jLabel73;
    private javax.swing.JLabel jLabel74;
    private javax.swing.JLabel jLabel75;
    private javax.swing.JLabel jLabel76;
    private javax.swing.JLabel jLabel77;
    private javax.swing.JLabel jLabel78;
    private javax.swing.JLabel jLabel79;
    private javax.swing.JLabel jLabel80;
    private javax.swing.JLabel jLabel81;
    private javax.swing.JLabel jLabel82;
    private javax.swing.JLabel jLabel83;
    private javax.swing.JLabel jLabel84;
    private javax.swing.JLabel jLabel85;
    private javax.swing.JLabel jLabel86;
    private javax.swing.JLabel jLabel87;
    private javax.swing.JLabel jLabel88;
    private javax.swing.JLabel jLabel89;
    private javax.swing.JLabel jLabel90;
    private javax.swing.JLabel jLabel91;
    private javax.swing.JLabel jLabel92;
    private javax.swing.JLabel jLabel93;
    private javax.swing.JLabel jLabel94;
    private javax.swing.JLabel jLabel95;
    private javax.swing.JLabel jLabelNomePesquisar;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanelCadastro;
    private javax.swing.JPasswordField jPasswordFieldSenha;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPaneCadastro;
    private javax.swing.JTable jTablePesquisarFuncionario;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField12;
    private javax.swing.JTextField jTextFieldBairro;
    private javax.swing.JTextField jTextFieldCargo;
    private javax.swing.JTextField jTextFieldCidade;
    private javax.swing.JTextField jTextFieldCodigo;
    private javax.swing.JTextField jTextFieldEmail;
    private javax.swing.JTextField jTextFieldEndereco;
    private javax.swing.JTextField jTextFieldEspecificar;
    private javax.swing.JTextField jTextFieldMae;
    private javax.swing.JTextField jTextFieldNaturalidade;
    private javax.swing.JTextField jTextFieldNome;
    private javax.swing.JTextField jTextFieldNumero;
    private javax.swing.JTextField jTextFieldPai;
    private javax.swing.JTextField jTextFieldPesquisarNome;
    private javax.swing.JTextField jTextFieldRua;
    private javax.swing.JTextField jTextFieldUf;
    // End of variables declaration//GEN-END:variables
}
